### ISSUE TITLE
'Command' object has no attribute 'broadcaster_id'

### ISSUE THREAD

**Issue by camjac251** [seriousm4x/django-twitch-archive#14]
I am trying to get this up and running but get an error when trying. It was working all right with Postgresql disabled but I wasn't able to see any styling and saw a few errors when it tried accessing the static files

Here's the main error I was seeing
```
dta-web | [2020-10-24 12:35:32 +0000] [31] [INFO] Starting gunicorn 20.0.4
dta-web | [2020-10-24 12:35:32 +0000] [31] [INFO] Listening at: http://0.0.0.0:8000 (31)
dta-web | [2020-10-24 12:35:32 +0000] [31] [INFO] Using worker: sync
dta-web | [2020-10-24 12:35:32 +0000] [36] [INFO] Booting worker with pid: 36
dta-web | [2020-10-24 12:35:33 +0000] [37] [INFO] Booting worker with pid: 37
dta-web | [2020-10-24 12:35:33 +0000] [38] [INFO] Booting worker with pid: 38
dta-web | HTTP error occurred: 400 Client Error: Bad Request for url: https://id.twitch.tv/oauth2/token?client_id=%3Cclient-id%3E&client_secret=%3Cclient-secret%3E&grant_type=client_credentials
dta-web | [2020-10-24 12:35:33 +0000] [39] [INFO] Booting worker with pid: 39
dta-web | Updated Twitch credentials
dta-web | Filling database with clips
dta-web | Traceback (most recent call last):
dta-web |   File "manage.py", line 22, in <module>
dta-web |     main()
dta-web |   File "manage.py", line 18, in main
dta-web |     execute_from_command_line(sys.argv)
dta-web |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
dta-web |     utility.execute()
dta-web |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
dta-web |     self.fetch_command(subcommand).run_from_argv(self.argv)
dta-web |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
dta-web |     self.execute(*args, **cmd_options)
dta-web |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
dta-web |     output = self.handle(*args, **options)
dta-web |   File "/opt/app/clips/management/commands/updateDB.py", line 62, in handle
dta-web |     self.updateClips()
dta-web |   File "/opt/app/clips/management/commands/updateDB.py", line 71, in updateClips
dta-web |     self.broadcaster_id), headers=self.kraken_header).json()["created_at"]
dta-web | AttributeError: 'Command' object has no attribute 'broadcaster_id'
dta-web | [2020-10-24 12:35:33 +0000] [40] [INFO] Booting worker with pid: 40
```

and the missing styling/images
```
dta-web | 2020-10-10T12:34:23.919786Z
dta-web | Not Found: /static/svg/logo.svg
dta-web | Not Found: /static/svg/clip-offline.svg
dta-web | Not Found: /media/game_thumbnails/510218.jpg
dta-web | Not Found: /static/svg/twitch.svg
dta-web | Not Found: /media/game_thumbnails/18122.jpg
dta-web | Not Found: /media/game_thumbnails/518184.jpg
dta-web | Not Found: /media/game_thumbnails/509658.jpg
dta-web | Not Found: /static/css/all.min.css
dta-web | Not Found: /static/css/bulma.min.css
dta-web | Not Found: /static/css/bulma-prefers-dark.css
dta-web | Not Found: /static/css/style.css
dta-web | Not Found: /static/js/navbar-toggle.js
dta-web | Not Found: /static/svg/logo.svg
dta-web | Not Found: /static/svg/clip-offline.svg
dta-web | Not Found: /media/game_thumbnails/510218.jpg
dta-web | Not Found: /static/svg/twitch.svg
dta-web | Not Found: /media/game_thumbnails/18122.jpg
dta-web | Not Found: /media/game_thumbnails/518184.jpg
dta-web | Not Found: /media/game_thumbnails/509658.jpg
````

**Comment by seriousm4x** [comment]
> dta-web | HTTP error occurred: 400 Client Error: Bad Request for url: https://id.twitch.tv/oauth2/token?client_id=%3Cclient-id%3E&client_secret=%3Cclient-secret%3E&grant_type=client_credentials

This indicates that the .env file wasn't set up correctly. Make sure to have client and client secret set up in your .env file and run run docker again with --build flag.

**Comment by camjac251** [comment]
It's weird. I had them in the env and it didn't give the error with `USE_POSTGRESQL=False`.
Do you mean running `docker-compose up --build`?

**Comment by seriousm4x** [comment]
Yes running docker-compose up -d --build copies all files into the container again (for changes on the .env file).

There are multiple ways to approach this

1. I would suggest deleting the Postgres db and start from scratch.

2. Even if the container gives you an error, the django backend should still be up and running. So you could navigate to example.com/admin/ and delete all entries under "twitch settings". Then restart the container.

3. If you want to migrate your existing database, you could also try to [dump](https://stackoverflow.com/a/11546254) the current sqlite db from within the container and import it to Postgres. The project automatically checks, if the file "datadump.json" exists in the root directory and imports it.
